# Generated by Django 3.2.9 on 2024-06-21 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20240620_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='hobbies',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.CreateModel(
            name='contentclassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.CharField(max_length=150)),
                ('blogtitle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.blog')),
                ('hobbies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userdetails')),
            ],
        ),
    ]
