# Generated by Django 3.2.9 on 2024-06-21 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20240621_2332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.CharField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='contentclassification',
        ),
    ]
