# Generated by Django 3.2.9 on 2024-06-21 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20240621_2335'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Search',
        ),
    ]
