# Generated by Django 3.2.9 on 2024-06-21 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_search'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='views',
        ),
        migrations.DeleteModel(
            name='ip',
        ),
    ]
