# Generated by Django 3.2.9 on 2024-06-21 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20240621_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ip',
            name='user',
        ),
    ]
