# Generated by Django 3.2.9 on 2024-06-23 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_ip_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ip',
            name='blogid',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
