# Generated by Django 3.2.9 on 2024-06-24 09:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0012_alter_ip_blogid'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='ipliked',
            field=models.ManyToManyField(related_name='ipliked', to='app.ip'),
        ),
        migrations.AddField(
            model_name='blog',
            name='userliked',
            field=models.ManyToManyField(related_name='userliked', to=settings.AUTH_USER_MODEL),
        ),
    ]
