# Generated by Django 3.2.9 on 2024-06-24 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_blog_ipliked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likeip',
            old_name='likeip',
            new_name='likedip',
        ),
    ]
