# Generated by Django 3.2.9 on 2024-06-25 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_comments_usercomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comments',
        ),
    ]
