# Generated by Django 3.2 on 2024-06-28 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='tagged_user',
            field=models.ManyToManyField(to='app.userdetails'),
        ),
    ]
