# Generated by Django 3.2 on 2024-07-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_blog_tagged_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='tagged_user',
            field=models.ManyToManyField(to='app.userdetails'),
        ),
    ]
