# Generated by Django 3.2 on 2024-09-12 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_blog_tagged_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ip',
            new_name='viewsip',
        ),
    ]
