# Generated by Django 3.2 on 2024-09-17 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_rename_ip_viewsip'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='likeip',
            new_name='like',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='likedip',
            new_name='liked_username',
        ),
    ]
