# Generated by Django 3.2 on 2024-09-17 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20240917_1145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='ipliked',
            new_name='liked_username',
        ),
    ]
