# Generated by Django 3.2 on 2024-09-17 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_rename_ipliked_blog_liked_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='liked_username',
        ),
        migrations.DeleteModel(
            name='like',
        ),
    ]
