# Generated by Django 3.2 on 2024-09-22 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_blog_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followers',
            name='followers_ip',
        ),
    ]
