# Generated by Django 3.2 on 2024-09-22 07:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0030_remove_followers_followers_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='followers',
            field=models.ManyToManyField(related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='followers',
        ),
    ]
